import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useCountdown } from "../hooks/use-countdown";
import styles from "../styles/Home.module.css";

const formatTime = (timer: number) => timer.toString().padStart(2, "0");

const Home: NextPage = () => {
  const {
    minutes,
    seconds,
    setStartCountdown,
    startCountDown,
    resetCountDown,
  } = useCountdown();

  const HandleInitCountdown = () =>
    startCountDown ? setStartCountdown(false) : setStartCountdown(true);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <span className={styles.text__timer}>{formatTime(minutes)}</span>
          <span className={styles.text__timer}>:</span>
          <span className={styles.text__timer}>{formatTime(seconds)}</span>
        </div>
        <div className={styles.container__button}>
          <button type="button" onClick={HandleInitCountdown}>
            {startCountDown ? "Pausar" : "Iniciar"}
          </button>
          <button type="button" onClick={resetCountDown}>
            Resetar
          </button>
        </div>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
